message_queue: 1000

sample_time: 0.001

A_system_matrix_height: 4
A_system_matrix_width: 4
A_system_matrix: [1,0,0.001,0,
                  0,1,0,0.001,
                  0,0,1,0,
                  0,0,0,1]

B_input_gain_height: 4
B_input_gain_width: 1
B_input_gain_matrix: [0,0.0000005,0,0.001]

c_measurement_matrix_height: 2
c_measurement_matrix_width: 4
c_measurement_matrix: [1,0,0,1,
                       0,0,0,0]

prior_state_height: 4
prior_state_width: 1
prior_state: [0,0,9,9]

input_state_height: 1
input_state_width: 1
input_state: [-9.8]

Q_process_noise_height: 4
Q_process_noise_width: 4
Q_process_noise: [0.001,0,0,0,
                  0,0.001,0,0,
                  0,0,0.001,0,
                  0,0,0,0.001]

prior_covariance_height: 4
prior_covariance_width: 4
prior_covariance: [1,0,0,0,
                   0,1,0,0,
                   0,0,1,0,
                   0,0,0,1]

R_measurement_noise_height: 2
R_measurement_noise_width: 2
R_measurement_noise: [1,0,
                      0,1]